# Generated by Django 5.0.6 on 2024-06-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_submission_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='ai_mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
