# Generated by Django 5.0.6 on 2024-06-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mark_ai_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='ai_mark',
            field=models.FloatField(default=0),
        ),
    ]
