# Generated by Django 5.0.6 on 2024-06-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mark_ai_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='teacher_mark',
            field=models.FloatField(default=0),
        ),
    ]
