# Generated by Django 5.0.6 on 2024-06-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mark_teacher_mark'),
        ('user', '0006_alter_studentprofile_user_alter_teacherprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
            options={
                'unique_together': {('student', 'test', 'attempt_number')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attempt'),
        ),
    ]
